### ISSUE TITLE
How to run this

### ISSUE THREAD

**Issue by Mr-Coxall** [dbaeumer/wasm-wasi-sample#2]
I have read over the blog post (https://code.visualstudio.com/blogs/2023/06/05/vscode-wasm-wasi) and have also tried the new VSCode for Education.

I would like to run my own version of this in the browser, but if I open the URL that you have on the blog post (https://insiders.vscode.dev/github/dbaeumer/wasm-wasi-sample) I can not access the Python Shell.

Any instructions?
Thanks

**Comment by dbaeumer** [comment]
You need to install the following two extensions from the marketplace:

https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-python-web-wasm
https://marketplace.visualstudio.com/items?itemName=ms-vscode.webshell

Please ping if something is still unclear.

This repository only hosts some Python sample code,

**Comment by Mr-Coxall** [comment]
Thanks so much.
I got a basic Python repo working (https://github.com/Mr-Coxall/Python-WASM-Test).
The only issue I have found is that when you debug, if it hits an ```input()``` function call then the debugger crashes. This seems odd since I have tried the edu Python website and it does work there.

Thanks again.
